class ArtifactNotFoundError(Exception): ...

class FailedFetchArtifactMuseumAPIException(Exception): ...

class FailedPublishArtifactMessageBrokerException(Exception): ...

class FailedPublishArtifactInCatalogException(Exception): ...
